# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Aunis alpha version

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Retrieve version and change beta to alpha
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        echo ::set-env name=AUNIS_VERSION_ONLY::$(grep mod_version gradle.properties | cut -d= -f2 | cut -d- -f1)
        sed -i "s/beta/alpha-`date +%Y-%m-%d`/g" gradle.properties
        echo ::set-env name=AUNIS_VERSION_DATE::$(grep mod_version gradle.properties | cut -d= -f2)
        echo ::set-env name=MC_VERSION::$(grep -E "^mc_version" gradle.properties | cut -d= -f2)
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.AUNIS_VERSION_DATE }}
        release_name: Release aunis-${{ env.AUNIS_VERSION_DATE }}
        draft: false
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/libs/aunis-${{ env.MC_VERSION }}-${{ env.AUNIS_VERSION_DATE }}.jar
        asset_name: aunis-${{ env.MC_VERSION }}-${{ env.AUNIS_VERSION_DATE }}.jar
        asset_content_type: application/x-java-archive
